# Generated by Django 5.1.6 on 2025-05-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_charterrecordbraemaroffshore_charterrecordwestshore_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharterRecordBraemaroffshore',
        ),
        migrations.DeleteModel(
            name='CharterRecordHowerobinsonoffshore',
        ),
        migrations.DeleteModel(
            name='CharterRecordWestshore',
        ),
    ]
